import io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/tutorial_java_projects.html
 */

buildscript {

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:2.1.4.RELEASE")
        classpath("gradle.plugin.org.jruyi.gradle:thrift-gradle-plugin:0.4.0")
    }
}

plugins {
    // Apply the java plugin to add support for Java
    java
    eclipse
    idea
}

apply {
    plugin("java")
    plugin("eclipse")
    plugin("idea")
    plugin("org.springframework.boot")
    plugin("io.spring.dependency-management")
}

val sourceCompatibility = "1.11"
val targetCompatibility = "1.11"

repositories {
    // Use mavenCentral for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
}

configure<DependencyManagementExtension> {
    imports {
        mavenBom("com.linecorp.armeria:armeria-bom:0.81.1")
    }
}


dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.boot:spring-boot-starter-jdbc")
    compile("org.sql2o:sql2o:1.6.0")
    compile("org.apache.commons:commons-dbcp2:2.6.0")
    compile("mysql:mysql-connector-java:6.0.6")

    // Armeria
    compile("com.linecorp.armeria:armeria")
    compile("com.linecorp.armeria:armeria-spring-boot-starter")
    compile("com.linecorp.armeria:armeria-tomcat")
    compile("com.linecorp.armeria:armeria-thrift")
    compile("org.apache.thrift:libthrift:0.12.0")

    // Use JUnit test framework
    testCompile("org.springframework.boot:spring-boot-starter-test")
}

